using System;

namespace com.gexin.rp.sdk.dto
{
    public enum CmdID
    {
        GTHEARDBT,
        GTAUTH,
        GTAUTH_RESULT,
        REQSERVHOST,
        REQSERVHOSTRESULT,
        PUSHRESULT,
        PUSHOSSINGLEMESSAGE,
        PUSHMMPSINGLEMESSAGE,
        STARTMMPBATCHTASK,
        STARTOSBATCHTASK,
        PUSHLISTMESSAGE,
        ENDBATCHTASK,
        PUSHMMPAPPMESSAGE,
        SERVERNOTIFY,
        PUSHLISTRESULT,
        SERVERNOTIFYRESULT,
        STOPBATCHTASK,
        STOPBATCHTASKRESULT,
        PUSHMMPSINGLEBATCH
    }
}
